### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by rnikoopour** [emacsorphanage/terraform-mode#28]
Hello I'd like to be the new maintainer for this project.

What are the steps involved?

**Comment by yamashita-optarc** [comment]
Thanks. I don't have the permission, so I think @tarsius will take care of it for you.

**Comment by tarsius** [comment]
Thanks for the offer!

I usually check existing elisp packages of the volunteer but I couldn't find any in your case. Please say a few words about your experience. I would suggest that you begin reviewing existing prs and tackle open issues, and I keep an eye on that. If you are unsure about something, then ask for a second pair of eyes.

**Comment by rnikoopour** [comment]
Hey @tarsius,

I help maintain https://github.com/emacs-lsp/lsp-docker/ 

I'm relatively new to writing `elisp` so I would appreciate any feedback on PRs.

I'll poke around the repo and see what I can work on.  

Cheers!

**Comment by tarsius** [comment]
I'll keep an eye on this, but if you have a concrete question, then please mention me explicitly.

**Comment by tarsius** [comment]
You've been promoted. :1st_place_medal:
