### ISSUE TITLE
Investigate Travis CI Cask issue

### ISSUE THREAD

**Issue by rnikoopour** [emacsorphanage/terraform-mode#34]
Travis CI is failing.  

Example failure: https://travis-ci.org/github/emacsorphanage/terraform-mode/builds/741800912

**Comment by rnikoopour** [comment]
@tarsius I requested access to the emacsorphanage org to integrate `travis-ci.com`.  

Currently the build is based on `travis-ci.org` which is shutting down.

**Comment by tarsius** [comment]
I have given you temporary admin rights for this repository only. If that isn't enough, then I will have to make the changes for you and would appreciate it if you could guide me through the process.

**Comment by rnikoopour** [comment]
I was able to send a request for access.  It looks like its pending approval from the org owners:

![Screen Shot 2020-11-18 at 8 25 39 AM](https://user-images.githubusercontent.com/7692789/99557786-eaad3900-2977-11eb-896e-895c68e9ac27.png)

**Comment by tarsius** [comment]
Should work now.

**Comment by rnikoopour** [comment]
Thanks for setting that part up.  

I've run into one more issue.  Since I'm not an org member, I cannot see/configure repos under `emacsorphanage` in Travis.  Would it be possible to become an org member or have an org member configure the build?

**Comment by tarsius** [comment]
> This application will be able to read and write all public and **private** repository data.

This is not gonna happen.

> Currently the build is based on `travis-ci.org` which is shutting down.

But it still works right now? (Until when?)

I am comfortable with the permissions requested by `travis-ci.org` as it doesn't want access to private repositories.

In the long run I think we should migrate to Github Actions instead.

**Comment by rnikoopour** [comment]
travis-ci.org is shutting down on 12/31/2020.

If we want to move to Github Actions I can investigate that instead of Travis.

**Comment by tarsius** [comment]
More links:
- https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
- https://www.theregister.com/2020/11/02/travis_ci_pricng

> If we want to move to Github Actions I can investigate that instead of Travis.

Please do that. I'll start investigating myself soon too.

**Comment by rnikoopour** [comment]
Closing this since we're migrating away from Travis.  #40 supersedes this issue.
