### ISSUE TITLE
Tag version 1?

### ISSUE THREAD

**Issue by Fuco1** [emacsorphanage/terraform-mode#56]
@rnikoopour I've processed all the pull requests and issues not opened by you (which are more of a discussion points anyhow).

I think we can just arbitrarily decide now to tag version 1.0.0 so things like melpa stable pick it up.  The package has enough features to be useful so I don't see a reason not to have a "version" release.

WDYT?

**Comment by rnikoopour** [comment]
Sounds good to me.  👍

**Comment by rnikoopour** [comment]
This is completed.  Closing.
