### ISSUE TITLE
Mode overwrites `C-h` which is special in emacs.

### ISSUE THREAD

**Issue by vspinu** [emacsorphanage/terraform-mode#57]
`C-h` is used throughout emacs to describe all key binding starting with current prefix. `terraform-mode` overwrites it in `C-c C-h`.  

I think it's customary to use `C-c C-d` for mode specific documentation.

**Comment by Fuco1** [comment]
Hmm, `C-c C-h` does nothing for me in elisp or other buffers.  But I don't see any problem rebinding this.

**Comment by vspinu** [comment]
Maybe you re-bind C-h locally. If I start `emacs -q` I do a help buffer popping on `C-h`. People these days use better interfaces like [helm-descbinds](https://github.com/emacs-helm/helm-descbinds), [embark](https://github.com/oantolin/embark) but they do still operate with `C-h` by default.

**Comment by dod38fr** [comment]
Even though `terraform-mode` is loaded, hitting `C-h` opens a help mini-buffer: 

![2023-05-24_15-49](https://github.com/emacsorphanage/terraform-mode/assets/1110441/74584074-8ebf-4b53-9f16-a20ba92773dd)

@vspinu Is that not what you expected ?

**Comment by vspinu** [comment]
@dod38fr It's about `C-c C-h`, it should describe the bindings not to open a web page or something else.

**Comment by dod38fr** [comment]
ok, I've seen the problem. I've updated my PR (#61 ) to change the key binding

**Comment by dod38fr** [comment]
> I've updated my PR (https://github.com/emacsorphanage/terraform-mode/pull/61 ) to change the key binding

@Fuco1 would you rather have a separate PR for this issue ?

**Comment by Fuco1** [comment]
@dod38fr No it's fine, thanks for also fixing this one!
