### ISSUE TITLE
C-c C-h on data block opens web page for resource

### ISSUE THREAD

**Issue by dod38fr** [emacsorphanage/terraform-mode#58]
Hello

When I hit `C-c C-h` on the following code:
```hcl
data "aws_iam_policy" "managed_policies" {
  name     = "example"
}
```

a new web page is opened on [aws_iam_policy resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy) page instead of [aws_iam_policy data](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy) page.

Could you fix terraform-mode so the right URL is opened ?

Thanks for maintaining terraform-mode

All the best

**Comment by tarsius** [comment]
> Could you fix terraform-mode so the right URL is opened ?
> Thanks for maintaining terraform-mode

Since I never used this package (and don't even know what it does), I do only very light maintenance. (There are 145 packages in the orphanage, and I cannot learn about all of them.)

But if you fix it yourself, and write a good commit message, then I would merge the pull-request.

**Comment by dod38fr** [comment]
Fair enough. I'll give it a try.

**Comment by vspinu** [comment]
C-c C-h is a wrong binding for this in the first place. It hijacks the C-h emacs postfix to describe map-bindings (#57)

**Comment by dod38fr** [comment]
All right, how about `C-c C-t C-h` ? `C-t` would stand for `terraform-mode` major mode.

For the record, here are Emacs [Key Binding Conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html)

**Comment by vspinu** [comment]
Documentation sits on C-c C-d normally. This one can be on C-c C-d C-w because it's a "web" resource not internal to emacs.
