### ISSUE TITLE
String interpolation breaks syntax highlightin.

### ISSUE THREAD

**Issue by MaikuMori** [emacsorphanage/terraform-mode#9]
Satements such as

``` hcl
resource "template_file" "ecs_deploy_policy" {
  template = "${path.module}/policies/ecs-deploy-policy.json"
}
```

and more convoluted 

``` hcl
resource "aws_iam_role_policy" "ecs_service_role_policy" {
  policy   = "${file("${path.module}/policies/ecs-service-role-policy.json")}"
}
```

breaks the syntax highlighting. Both are valid HSL statements. I find the not escaping double quotes in double quotes quite strange, but to my understanding that's how it is intended.

**Comment by Fuco1** [comment]
This is a hcl-mode issue, I've opened an issue upstream.
